### ISSUE TITLE
Add capital limits on the pool

### ISSUE THREAD

**Issue by mzs-dev** [askibin/perpetuals#11]
Do we want to limit the total pool size and cap token deposits in accordance with a prefixed usd_value?
This could be part of the overall risk management strategy and should be ideally facilitated by design.

**Comment by askibin** [comment]
there is a cap that is based on the token weights, but there is no general cap based on the usd value. It is easy to add, but what would be the reason to enable such cap? To limit potential risks during the beta testing period?

**Comment by mzs-dev** [comment]
The cap based on token weights is rather a default fail-safe mechanism. The actual reasoning behind a cap based on usd value is to limit the pool exposure on the short side where the pool would be indebted in absolute terms, causing the pool to lose nominal USD value when a trader closes a short position with +ve pnl. In contrast, on the long side the pool expousre is limited only to the potential upside by upwards price action of the asset when a long position is closed with +ve pnl.

**Comment by askibin** [comment]
in both cases (long and short) protocol's loss is limited to position_size * max_payoff_mult
Given the same price action, protocol loses a bit less for long positions because amount of the collateral returned is determined based on the fixed usd value, but that extra saving is equal to open_price/close_price * collateral_usd, if leverage is high, the difference between long and short loss is not that noticeable. I'll add the cap anyway, but let me know if I'm still missing what risk you are trying to mitigate.

**Comment by mabrehan** [comment]
A cap on utilization can also be helpful to get make sure that the pool always has sufficient liquidity to process withdrawal requests(remove_liquidity), even during the time of high demand
